name: CI and CD

on: 
  push:
     branches:
      - master
  pull_request:
     branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master      
    - uses: actions/setup-node@master
    - name: Update package version and setup git
    - run: lerna bootstrap
    - run: "npm publish --registry-url: https://npm.pkg.github.com/ --scope: '@leofalco'"
      working-directory: packages/foo
      env:
        GH_PACKAGES_TOKEN: ${{github.GH_PACKAGES_TOKEN}}

