name: CI and CD

on: 
  push:
     branches:
      - master
  pull_request:
     branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master      
    - uses: actions/setup-node@master
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Git Identity
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    - run: npx lerna bootstrap
    - run: npx lerna run test
    - run: npx lerna version --conventional-commits -y  
    - run: npx lerna publish from-package -y --registry=https://npm.pkg.github.com/ 