name: CI and CD

on: 
  push:
     branches:
      - master
  pull_request:
     branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}W
    steps:
    - uses: actions/checkout@master      
    - uses: actions/setup-node@master
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npx lerna bootstrap
    - run: npx lerna run test
    - run: npx lerna version --conventional-commits -y  
    - run: npx lerna publish from-package -y --registry=https://npm.pkg.github.com/ 