name: CI and CD

on: 
  push:
     branches:
      - master
  pull_request:
     branches:
      - '**'

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npx lerna bootstrap
      - run: npx lerna run test
      - run: echo ${{ github.ref }}

      - name: Configure Git
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'Leo Falco'
          git config --global user.email 'leonardo.falco@outlook.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/leoFalco/foo
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - run: npm publish
        working-directory: packages/foo

      - run: npx lerna publish from-package -y
        if: github.ref == 'refs/heads/master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
